### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by Viniciusalopes** [mazonos/mz#1]
root [ /sbin ]# mz update
Updating -Traceback (most recent call last):
  File "/sbin/mz", line 237, in <module>
    functions[choose]()
  File "/sbin/mz", line 218, in update
    with open(filecsv, 'a') as new_file:
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/mz/mz_base.csv'
Updating /^CException ignored in: <module 'threading' from '/usr/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 1273, in _shutdown
    t.join()
  File "/usr/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt

**Comment by Viniciusalopes** [comment]
Possível solução:
Faltava o diretório `/var/lib/mz`.
Criei na mão com a ajuda do Santo Rumbler e funcionou!!

**Comment by 4lnx** [comment]
Fechado, correção seguiu no pull request efd1e18caef7517a9366da70aecff693eab6ac7d
